// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAysyKaQlOxo50fEJziXKga5Jslx2_KMCo',
    appId: '1:927434418225:web:75a60ef802077a1e3d8d10',
    messagingSenderId: '927434418225',
    projectId: 'diabetes-management-d1791',
    authDomain: 'diabetes-management-d1791.firebaseapp.com',
    storageBucket: 'diabetes-management-d1791.firebasestorage.app',
    measurementId: 'G-T06G6SSZ4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLCoq8UpxjaeQbVAIWWbH5QC81UmsLyYk',
    appId: '1:927434418225:android:61a0debb2201a6033d8d10',
    messagingSenderId: '927434418225',
    projectId: 'diabetes-management-d1791',
    storageBucket: 'diabetes-management-d1791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCANVnHBChVuMwRweqIRIRodHNMewXS5CM',
    appId: '1:927434418225:ios:55798cef7c44f36a3d8d10',
    messagingSenderId: '927434418225',
    projectId: 'diabetes-management-d1791',
    storageBucket: 'diabetes-management-d1791.firebasestorage.app',
    iosBundleId: 'com.example.diabetesManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCANVnHBChVuMwRweqIRIRodHNMewXS5CM',
    appId: '1:927434418225:ios:55798cef7c44f36a3d8d10',
    messagingSenderId: '927434418225',
    projectId: 'diabetes-management-d1791',
    storageBucket: 'diabetes-management-d1791.firebasestorage.app',
    iosBundleId: 'com.example.diabetesManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAysyKaQlOxo50fEJziXKga5Jslx2_KMCo',
    appId: '1:927434418225:web:c12c0ca501a6d6863d8d10',
    messagingSenderId: '927434418225',
    projectId: 'diabetes-management-d1791',
    authDomain: 'diabetes-management-d1791.firebaseapp.com',
    storageBucket: 'diabetes-management-d1791.firebasestorage.app',
    measurementId: 'G-NKKBPJMQDT',
  );

}