// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC7IhZ3I05A_1ld-SBd4z-fVUvlCRi8PI',
    appId: '1:988076890118:web:818a12420b82a314760b87',
    messagingSenderId: '988076890118',
    projectId: 'mpauni',
    authDomain: 'mpauni.firebaseapp.com',
    storageBucket: 'mpauni.firebasestorage.app',
    measurementId: 'G-0SLSJ1GSX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj5cSOUGrfhZAxi3R2rOSL391-q-8sscQ',
    appId: '1:988076890118:android:9b0217002e99649e760b87',
    messagingSenderId: '988076890118',
    projectId: 'mpauni',
    storageBucket: 'mpauni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYGvh0qXH4z39QFoZxI4igAW4c360bsAE',
    appId: '1:988076890118:ios:7f50b331477b0c3f760b87',
    messagingSenderId: '988076890118',
    projectId: 'mpauni',
    storageBucket: 'mpauni.firebasestorage.app',
    iosBundleId: 'com.example.diabetesManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYGvh0qXH4z39QFoZxI4igAW4c360bsAE',
    appId: '1:988076890118:ios:7f50b331477b0c3f760b87',
    messagingSenderId: '988076890118',
    projectId: 'mpauni',
    storageBucket: 'mpauni.firebasestorage.app',
    iosBundleId: 'com.example.diabetesManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC7IhZ3I05A_1ld-SBd4z-fVUvlCRi8PI',
    appId: '1:988076890118:web:37c70ba70a399cc8760b87',
    messagingSenderId: '988076890118',
    projectId: 'mpauni',
    authDomain: 'mpauni.firebaseapp.com',
    storageBucket: 'mpauni.firebasestorage.app',
    measurementId: 'G-RC833NE14W',
  );
}
